import { Component } from '@angular/core';
import { Router } from '@angular/router';
import { PassandoDadosService } from '../servicos/passando-dados.service';

@Component({
  selector: 'app-tab2',
  templateUrl: 'tab2.page.html',
  styleUrls: ['tab2.page.scss']
})
export class Tab2Page {

  public cursos = [
    {
      nome: 'Ensino Médio',
      conteudo: '<img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/AlunosAprovadosEM-768x576.jpg"/><p>O Ensino Médio, etapa final da educação básica, com duração mínima de três anos aprofunda os conhecimentosadquiridos no ensino fundamental, possibilitando o prosseguimento de estudos.</p> <img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/ShowDaEtec-768x432.jpg" /> <p>O currículo do Ensino Médio além dos conhecimentos gerais inclui uma Língua Estrangeira Moderna, Filosofia e Sociologia como disciplinas obrigatórias em todas as séries do Ensino Médio. Como parte diversificada, a escola adota para as três séries o Inglês como Língua Estrangeira Moderna. Nas 2ª séries, os conhecimentos de Sociologia são desenvolvidos na Disciplina Educação para cidadania, projeto que contempla o estudo das leis básicas que constituem o Estado democrático, as que estabelecem os direitos e deveres dos cidadãos e dos governos e as leis que disciplinam a administração pública. O projeto ainda abrange temáticas desde o questionamento da cidadania negada – exclusão, acessibilidade e direitos humanos.</p>',
      link: '/curso-numero/1'
    },
    {
      nome: 'Ensino Integrado', conteudo: '<img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/TroteEM.jpg" /> <p>O Ensino Técnico Integrado ao Médio, além de abranger as disciplinas regulares da última etapa do ensino básico, as integra ao ensino técnico, em nossa escola, ao curso de Informática para Internet, visando também a formação profissional do aluno, que é responsável por desenvolver programas de computador para internet seguindo as especificações e paradigmas da lógica e das linguagens de programação, identifica e usa fontes e documentos específicos para a obtenção das informações desejadas.</p> <p>São elaborados projetos interdisciplinares entre as disciplinas do Ensino Médio e Técnico, trabalhos que são apresentados anualmente tanto na Semana Científica e Cultural como na Semana das Profissões, eventos abertos à comunidade com salas interativas e aulas experimentais.</p> <ul> <li>O primeiro estuda situações- problemas relacionados à vida cotidiana do aluno de forma a proporcionar a capacidade de compreender o mundo ao seu redor.</li><li> O segundo, além de divulgar o curso, tem como finalidade auxiliar os educandos na escolha profissional,informando sobre perfil profissional, empregabilidade, faixa salarial e o que se estuda no curso técnico oferecido pela escola.Ambos eventos contribuem para trabalhar o espírito em equipe, a comunicação, as adversidades, flexibilidade, liderança, iniciativa, comportamento ético, para que o desenvolvimento das competências e habilidades seja pleno.</li> </ul><p> Para a divulgação do curso promove - se no segundo semestre o evento “Etec de portas abertas”.Também aberto à comunidade, a equipe gestora, pedagógica e docente apresentam as instalações da escola, as disciplinas e as respectivas habilidades e competências contempladas no plano docente.</p>',
      link: '/curso-numero/2'
    },
    {
      nome: 'Administração', conteudo: '<h1>Habilitação profissional</h1><p>O TÉCNICO EM ADMINISTRAÇÃO é o profissional que adota postura ética na execução da rotina administrativa, na elaboração do planejamento da produção e materiais, Recursos Humanos, financeiros e mercadológicos.</p><p>Realiza atividades de controles e auxilia nos processos de direção utilizando ferramentas da informática básica. Fomenta ideias e práticas empreendedoras. Desempenha suas atividades observando as normas de segurança, saúde e higiene do trabalho, bem como as de preservação ambiental.</p><h2>Mercado de trabalho</h2><p>Instituições públicas, privadas e do terceiro setor.<p><img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/Administracao-768x508.jpg"/><h1>Módulo I</h1><ul><li>Gestão de Pessoas</li><li>Cálculos Financeiros</li><li>Gestão Empresarial</li><li>Ética e Cidadania Organizacional</li><li>Aplicativos Informatizados</li><li>Processos Operacionais Contábeis</li><li>Linguagem, Trabalho e Tecnologia</li><li>Técnicas Organizacionais</li></ul><h1>Módulo II</h1><ul><li>Gestão de Pessoas II</li><li>Administração em Marketing</li><li>Legislação Empresarial</li><li>Custos e Operações Contábeis</li><li>Cálculos Estatísticos</li><li>Gestão Empreendedora e Inovação</li><li>Planejamento do Trabalho de Conclusão de Curso (TCC) em Administração</li></ul><h1>Módulo III</h1><ul><li>Marketing Institucional</li><li>Gestão Financeira e Econômica</li><li>Gestão de Pessoas III</li><li>Gestão da Produção e Materiais</li><li>Logística Empresarial e Negociação Internacional</li><li>Inglês Instrumental</li><li>Desenvolvimento do Trabalho de Conclusão de Curso (TCC) em Administração</li></ul>',
      link: '/curso-numero/3'
    },
    {
      nome: 'Contabilidade', conteudo: '<h1>Habilitação profissional</h1><p>O TÉCNICO EM CONTABILIDADE é o profissional que desempenha tarefas relativas à contabilidade e auxilia a administração das entidades. Analisa a documentação contábil e elabora o plano de contas.</p><p>Organiza, controla e arquiva documentos relativos à atividade contábil e prepara as conciliações contábeis. Registra as operações de débito e crédito da empresa, ordenando os movimentos de partidas simples e dobradas.</p><p>Prepara a documentação, apura haveres, direitos e obrigações legais. Constitui e regulariza empresas, examina e classifica documentos fiscais e parafiscais. Auxilia no atendimento à fiscalização e precede a consultoria empresarial. Executa a contabilidade geral, operacionaliza a contabilidade de custos, efetua contabilidade gerencial e realiza controle patrimonial.</p><h2>Mercado de trabalho</h2><p>Trabalhar em escritórios de contabilidade, em departamentos de contabilidade de empresas agrícolas, comerciais,industriais e de serviços, do terceiro setor e em órgãos governamentais.</p><img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/Contabilidade-768x452.jpg" /><h1>Módulo I</h1><ul><li>Aplicativos Informatizados</li><li>Ética e Cidadania Organizacional</li><li>Gestão de Documentos Contábeis</li><li>Contabilidade Introdutória</li><li>Direito Comercial e Empresarial</li><li>Linguagem, Trabalho e Tecnologia</li><li>Operações Financeiras</li><li>Economia e Mercado Financeiro</li><li>Legislação Social e Trabalhista</li></ul><h1>Módulo II</h1><ul><li>Contabilidade Comercial</li><li>Contabilidade de Custos</li><li>Contabilidade Intermediária</li><li>Sistemas de Informações Contábeis</li><li>Planejamento Estatísticos de Pesquisa</li><li>Inglês Instrumental</li><li>Planejamento do Trabalho de Conclusão de Curso (TCC) em Contabilidade</li></ul><h1>Módulo III</h1><ul><li>Contabilidade Gerencial e Estratégica</li><li>Tópicos Especiais de Contabilidade</li><li>Contabilidade Tributária e Fiscal</li><li>Estrutura e Análise das Demonstrações Financeiras</li><li>Contabilidade Pública</li><li>Contabilidade do Agronegócio</li><li>Desenvolvimento do Trabalho de Conclusão de Curso (TCC) em Contabilidade</li></ul>',
      link: '/curso-numero/4'
    },
    {
      nome: 'Desenvolvimento de Sistemas', conteudo: '<p>O TÉCNICO EM DESENVOLVIMENTO DE SISTEMAS é o profissional que analisa e projeta sistemas. Constrói, documenta, realiza testes e mantém sistemas de informação. Utiliza ambientes de desenvolvimento e linguagens de programação específica. Modela, implementa e mantém bancos de dados.</p><h1>Mercado de trabalho</h1><p>Empresas e departamentos de desenvolvimento de sistemas em organizações governamentais e não governamentais, podendo também atuar como profissional autônomo.</p><img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2019/05/ds.jpg"/><h1>Módulo I</h1><ul><li>Linguagem, Trabalho e Tecnologia</li><li>Programação e Algoritmos</li><li>Banco de Dados I</li><li>Análise e Projeto de Sistemas</li><li>Design Digital</li><li>Programação Web I</li><li>Fundamentos da Informática</li><li>Técnicas de Programação</li></ul><h1>Módulo II</h1><ul><li>Inglês Instrumental<li>Desenvolvimento de Sistemas</li><li>Banco de Dados II</li><li>Internet e Protocolos</li><li>Programação de Aplicativos Mobile I</li><li>Programação Web II</li><li>Planejamento do Trabalho de Conclusão de Curso (TCC)</li></ul><h1>Módulo III</h1><ul><li>Segurança de Sistemas de Informação</li><li>Banco de Dados III</li><li>Sistemas Embarcados</li><li>Programação de Aplicativos Mobile II</li><li>Programação Web III</li><li>Qualidade e Teste de Software</li><li>Ética e Cidadania Organizacional</li><li>Desenvolvimento do Trabalho de Conclusão de Curso (TCC)</li></ul>',
      link: '/curso-numero/5'
    },
    {
      nome: 'Marketing', conteudo: '<h1>Habilitação profissional</h1><p>O TÉCNICO EM MARKETING é o profissional ético que colabora na elaboração do plano de marketing da empresa, de acordo com seu ramo ou porte, tendo a competência aliada ao domínio técnico e no planejamento e implementação de ações de vendas e ações de mercado. Executa tarefa de análise das vendas, preços e produtos.</p><p>Operacionaliza as políticas de comunicação da empresa: fidelização de clientes, relação com fornecedores ou outras entidades. Operacionaliza políticas de apresentação dos produtos no ponto de venda.</p><p>Executa o controle, estatísticas e operações de telemarketing. Participa na elaboração e na realização de estudos de mercado, interpreta e aplica a legislação da área.</p><h2>Mercado de trabalho</h2><p>Instituições públicas; privadas e do terceiro setor; comércio; empresas de consultoria e de forma autônoma.</p><img src="http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/Marketing-768x431.jpeg"/><h1>Módulo I</h1><ul><li>Introdução ao Marketing</li><li>Legislação de Mercado</li><li>Comunicação Mercadológica</li><li>Comportamento do Consumidor</li><li>Aplicativos Informatizados</li><li>Gestão de Vendas I</li><li>Pesquisa de Mercado</li><li>Administração Financeira</li></ul><h1>Módulo II</h1><ul><li>Gestão de Vendas II</li><li>Técnicas de Informação e Comunicação Mercadológica</li><li>Inglês Instrumental I</li><li>Linguagem, Trabalho e Tecnologia</li><li>Espanhol Instrumental I</li><li>Estratégias de Marketing</li><li>Informática Aplicada ao Marketing</li><li>Planejamento do Trabalho de Conclusão de Curso (TCC) em Marketing</li></ul><h1>Módulo III</h1><ul><li>Canais de Distribuição</li><li>Marketing Institucional</li><li>Empreendedorismo</li><li>Plano de Comunicação</li><li>Ética e Cidadania Organizacional</li><li>Espanhol Instrumental II</li><li>Inglês Instrumental II</li><li>Desenvolvimento do Trabalho de Conclusão de Curso (TCC) em Marketing</li></ul>',
      link: '/curso-numero/6'
    },
    {
      nome: 'Secretariado', conteudo: '<h1>Habilitação profissional</h1><p>O TÉCNICO EM SECRETARIADO é o profissional que assessora o (os) executivo (os) em linguagem nacional e internacional, aplicando as técnicas secretariais que subsidiarão o (os) executivo (os) na tomada de decisões, inclusive para o planejamento estratégico, tático, operacional e Plano Diretor.</p><p>Exerce funções gerenciais; empreendedoras; práticas inovadoras; ações proativas; comprometido com a cultura organizacional; gerencia o fluxo de informações: produção documental física e eletrônica, conferência da documentação com ênfase no apoio à gestão organizacional.</p><p>Domina aplicativos e Internet na pesquisa, organização, elaboração, atualização e manutenção de dados.</p><h2>Mercado de trabalho</h2><p>Instituições, públicas, privadas, mistas e do terceiro setor: indústrias, prestadoras de serviços e comércio.</p><h1>Módulo I</h1><ul><li>Representação e Comunicação em Língua Portuguesa I</li><li>Representação e Comunicação em Língua Estrangeira Moderna: Espanhol I</li><li>Representação e Comunicação em Língua Estrangeira Moderna: Inglês I</li><li>Administração e Planejamento Empresarial</li><li>Gerenciamento de Rotinas e Serviços</li><li>Gestão de Informações e Documentos</li><li>Aplicativos Informatizados I</li><li>Ética e Cidadania Organizacional</li></ul><h1>Módulo II</h1><ul><li>Representação e Comunicação em Língua Portuguesa II</li><li>Representação e Comunicação em Língua Estrangeira Moderna: Espanhol II</li><li>Representação e Comunicação em Língua Estrangeira Moderna: Inglês II</li><li>Assessoria Empresarial e de Eventos</li><li>Tecnologias em Ambientes Administrativos I</li><li>Gestão Financeira e Contábil</li><li>Aplicativos Informatizados II</li><li>Planejamento do Trabalho de Conclusão de Curso (TCC) na Área Secretarial</li></ul><h1>Módulo III</h1><ul><li>Representação e Comunicação em Língua Portuguesa III</li><li>Representação e Comunicação em Língua Estrangeira Moderna: Espanhol III</li><li>Representação e Comunicação em Língua Estrangeira Moderna: Inglês III</li><li>Assessoramento Empresarial</li><li>Aplicativos Informatizados III</li><li>Assessoramento de Eventos</li><li>Tecnologias em Ambientes Administrativos</li><li>Desenvolvimento do Trabalho de Conclusão de Curso (TCC) na Área Secretarial</li></ul>',
      link: '/curso-numero/7'
    }
  ]

  constructor(private rota: Router, private enviaDado: PassandoDadosService) {
  }

  public mostraCurso(curso) {
    this.enviaDado.setDados('curso', curso);
    this.rota.navigate(['/detalhes-curso']);
  }
}
