import { Component, OnInit } from '@angular/core';
import { Router } from '@angular/router';
import { PassandoDadosService } from '../servicos/passando-dados.service';

@Component({
  selector: 'app-tab1',
  templateUrl: 'tab1.page.html',
  styleUrls: ['tab1.page.scss']
})
export class Tab1Page {

  public noticias = [
    {titulo:'Etec de Portas Abertas para a comunidade', img:'http://www.etecbarrabonita.com.br/wp-content/uploads/2018/11/EtecPortasAbertas.jpg', 
    resumo:'Em mais uma edição do evento Etec de Portas Abertas, realizado segunda-feira, 29 de outubro...',
     conteudo:'Em mais uma edição do evento Etec de Portas Abertas, realizado segunda-feira, 29 de outubro, tivemos a oportunidade de novamente proporcionar à comunidade e estudantes da região uma visão sobre nossos cursos, instalações e projetos pedagógicos.',
    Link:'/por-numero/1'},
    {titulo: 'Inscrições abertas para o Processo Seletivo Simplificado de Docentes', img:'http://www.camarabarrabonita.sp.gov.br/Arquivos/Noticias/2016121_IMG_4876.JPG', 
    resumo:'ATENÇÃO ::: As inscrições para o Processo Seletivo Simplificado de Docentes, Aviso nº 040/03/2019, serão reabertas a partir de 03/06/2019 à 17/06/2019',
    conteudo:'ATENÇÃO ::: As inscrições para o Processo Seletivo Simplificado de Docentes, Aviso nº 040/03/2019, serão reabertas a partir de 03/06/2019 à 17/06/2019, de segunda a sexta, no horário das 08h às 11h; das 14h30min às 16h30min e das 19h às 21h, os componentes são: <ul><li>Linguagem, Trabalho e Tecnologia</li><li>Inglês Instrumental</li><li>Artes</li><li>Física</li><li>Matemática</li><li>Química</li><li> Língua Estrangeira Moderna – Espanhol</li><li>Língua Estrangeira Moderna – Inglês e Comunicação Profissional </li><li>Representação e Comunicação em Língua Portuguesa II</li><li> Representação e Comunicação em Língua Estrangeira Moderna: Inglês III</li></ul>Para a inscrição e entendimento das fases do Processo Seletivo Simplificado há necessidade da leitura dos editais do Aviso 040/03/2019, disponíveis em : <a href="http://www.etecbarrabonita.com.br/processo-seletivo/">http://www.etecbarrabonita.com.br/processo-seletivo/</a>',
    link:'/por-numero/2'},
    {titulo: 'Etec Programa Novotec Expresso!', img:'https://media.licdn.com/dms/image/C4E1BAQGvKB7ixG0wGA/company-background_10000/0?e=2159024400&v=beta&t=7di1X8T86ZMaqXOBJyySn1J0N90i9LTnMs9kQo7jHzk',
     resumo:'Agora você pode estudar na Etec pelo Programa Novotec Expresso! Já estão abertas as inscrições para o programa de cursos rápidos profissionalizantes do Novotec Expresso',
     conteudo:'Agora você pode estudar na Etec pelo Programa Novotec Expresso! Já estão abertas as inscrições para o programa de cursos rápidos profissionalizantes do Novotec Expresso para alunos do Ensino Médio (1º, 2º ou 3º) da Rede Pública Estadual  Na Etec Comendador João Rays de Barra Bonita serão oferecidos os cursos:<ul><li>Excel Aplicado à Área Administrativa – Tarde </li><li>Computação na Nuvem – Tarde</li></ul>Previsão de início das aulas 01/08/2019. <br> Serão10 aulas semanais (distribuídas em dois ou três dias) <br> Carga horária total: 200 horas <br> Inscrições até dia 16/06/2019 pelo site: <a href="www.novotec.sp.gov.br">www.novotec.sp.gov.br</a> Cursos Gratuitos <br> Informações pelo site ou telefone (14) 3641-1310',
     link:'/por-numero/3'},
    {titulo: 'Arraiá da Navar', img:'http://www.s2noticias.com.br/arquivos/noticias/4652/x9e90d1b6cfa3f77ccd1c93bdfcc88af0.jpg.pagespeed.ic.MOFs9nKSbF.webp', resumo:'Convites à venda com os alunos da escola. Valor antecipado: R$10,00',
    conteudo:'<ul><li> Permitida a entrada de maiores de 16 anos desacompanhados; </li><li>Permitida a entrada de menores de 16 anos, somente acompanhados pelos pais ou responsável legal portando, obrigatoriamente, termo de guarda; </li><li>ATENÇÃO: A apresentação de documento de identidade original é obrigatória para todas as idades; </li><li>Proibida a entrada de bebidas alcoólicas. </li></ul> Mais informações: (14) 3641-1310<br>Participe!',
    link:'/por-numero/4'},
    {titulo: 'ETEC Vestibulinho 2019: Locais de provas são divulgados', img:'https://comapalavra.com.br/wp-content/uploads/2018/04/etec-678x381.jpg',
     resumo:'Os locais de provas já podem ser consultados',
     conteudo:'<p>A Escola Técnica Estadual de São Paulo (ETEC), instituição de ensino técnico, médio e técnico integrado ao médio, abriu edital de processo seletivo com diversas vagas em diversos níveis.</p><p>Os interessados puderam se inscrever de 10 de abril até as 15 horas do dia 15 de maio de 2019, no site oficial ( www.vestibulinhoetec.com.br). A taxa de inscrição custou R$30,00</p><p>O Exame está previsto para o dia 16 de junho. Os locais de provas já podem ser consultados </p><p>Veja O cronograma completo:</p><ul><li>De 28/03 até as 15h do dia 09/04/2019 – Inscrições para redução da taxa do Vestibulinho e envio por meio digital, via upload, da documentação comprobatória, no site www.vestibulinhoetec.com.br</li><li>De 10/04 até as 15h do dia 15/05/2019 – Inscrições do Processo Seletivo no site www.vestibulinhoetec.com.br</li><li>A partir de 30/04/2019 – Divulgação no site www.vestibulinhoetec.com.br do resultado da solicitação de redução da taxa de inscrição</li><li>De 30/04 até as 15h do dia 15/05/2019 – Inscrição para quem solicitou a redução da taxa de inscrição</li><li>11/06/2019 – Divulgação dos locais de Exame</li><li>16/06/2019, às 13h30min – Exame</li><li>16/06/2019 (domingo), a partir das 18h – Divulgação do gabarito oficial no site www.vestibulinhoetec.com.br</li><li>17/06/2019 (segunda-feira), a partir das 14h – Divulgação do gabarito oficial para acesso as vagas remanescentes no site www.vestibulinhoetec.com.br.</li><li>18/06/2019 (terça-feira), a partir das 14h – Divulgação do gabarito oficial dos Cursos de Especialização no site www.vestibulinhoetec.com.br.</li><li>05/07/2019 – Divulgação da lista de classificação geral para os cursos técnicos com prova de aptidão</li><li>16/07/2019 – Divulgação da lista de classificação geral dos demais cursos</li><li>17/07 e 18/07/2019 – Divulgação da 1ª lista de convocação e matrícula</li><li>19/07/2019 – Divulgação da 2ª lista de convocação</li><li>22/07 e 23/07/2019 – Matrícula da 2ª lista de convocação</li></ul>',
     link:'/por-numero/5'},
    {titulo: 'Etec de Barra Bonita realiza 24.ª Semana Científica e Cultural', img:'https://comapalavra.com.br/wp-content/uploads/2018/04/etec-678x381.jpg',
     resumo:'A Escola Técnica Estadual (Etec) Comendador João Rays, em Barra Bonita, realiza entre quinta (13) e sexta-feira (14) a 24.ª Semana Científica e Cultural.',
     conteudo:'<p>A Escola Técnica Estadual (Etec) Comendador João Rays, em Barra Bonita, realiza entre quinta (13) e sexta-feira (14) a 24.ª Semana Científica e Cultural. Aberto à toda comunidade, o evento deste ano tem como tema "Humanidade em nós: o valor feminino".</p><p>Durante os dois dias, será possível visitar salas temáticas e conhecer diversos projetos de alunos, como "O valor feminino", "A arte e o protagonismo da mulher na sociedade" e "No es no".</p><p>A programação de outros ambientes inclui as exposições "Maio de 68: o ano que não terminou", sobre os protestos iniciados por jovens estudantes na França que se espalharam pelo mundo; "Elas", destacando a construção cultural, social e histórica das noções de feminilidade e feminino; e "Ciências: o mundo em nossas mãos", que apresentará experimentos de Física e Química.</p><p>A Semana também contará com esquetes teatrais - pequenas peças ou cenas, geralmente cômicas - baseadas no livro "Quarto de Despejo, Diário de uma Favelada", de Carolina Maria de Jesus, escrito em 1960. Haverá ainda apresentações de dança.</p>',
     link:'/por-numero/6'},
    {titulo: 'Inscrições para vestibulinho da Etec são prorrogadas até dia 20', img:'http://www.etecbarrabonita.com.br/wp-content/uploads/2017/04/FachadaEtec-e1494419696829.jpg',
     resumo:'As inscrições para o processo seletivo das Escola Técnicas Estaduais foram prorrogadas até segunda-feira (20). O exame será no dia 16 de junho.',
     conteudo:'<p>As inscrições para o processo seletivo das Escola Técnicas Estaduais foram prorrogadas até segunda-feira (20).</p><p>Os interessados devem se inscrever pelo site do vestibulinho. O exame será no dia 16 de junho. Na região, as vagas são distribuídas entre ensino médio, médio integrado ao técnico e técnico.</p><p>O candidato deve preencher a ficha de inscrição eletrônica e imprimir o boleto bancário para pagamento da taxa de R$ 30. O valor deve ser pago em dinheiro, em qualquer agência bancária.</p><p>Para se inscrever em um dos cursos técnicos oferecidos no segundo semestre, o candidato precisa ter concluído ou estar cursando a partir do segundo ano do Ensino Médio.</p>',
     link:'/por-numero/7'},
    {titulo: 'Etec representada nas Seletivas para Olimpíadas Internacionais de Astronomia', img:'http://www.etecbarrabonita.com.br/wp-content/uploads/2018/11/201811-Olimpiada-Brasileira-de-Astronomia.jpeg',
     resumo:'Na edição 2018 da OBA – Olimpíada Brasileira de Astronomia e Astronáutica, os alunos da Etec Comendador João Rays – Barra Bonita se destacaram com excelentes resultados.',
     conteudo:'<p>Na edição 2018 da OBA – Olimpíada Brasileira de Astronomia e Astronáutica, os alunos da Etec Comendador João Rays – Barra Bonita se destacaram com excelentes resultados.</p><p>Paulo Cesar Ferrarez Filho conquistou medalha de bronze e Vitor Francisco Pullini, a medalha de prata, tendo se classificado para participar das seletivas para formação das equipes que representarão o Brasil na Olimpíada Internacional de Astronomia e Astrofísica, e na Olimpíada Latino Americana de Astronomia e Astronáutica, que serão realizadas em 2019.</p><p>Parabéns Paulo e Vitor, por essa importante conquista. E continuaremos na torcida pelo Vitor, para que consiga representar bem o Brasil.</p>',
     link:'/por-numero/8'},
    {titulo: 'Exame do Vestibulinho das Etecs deste domingo começa às 13h30', img:'https://www.cps.sp.gov.br/wp-content/uploads/sites/1/2019/06/19.0614-Lembrete-prova-Vestibulinho-580x420.jpg',
     resumo:'Começa às 13h30 do próximo domingo, dia 16, a prova do processo seletivo das Escolas Técnicas Estaduais (Etecs) para o segundo semestre de 2019, que terá quatro horas de duração.',
     conteudo:'<p>Começa às 13h30 do próximo domingo, dia 16, a prova do processo seletivo das Escolas Técnicas Estaduais (Etecs) para o segundo semestre de 2019, que terá quatro horas de duração.</p><p>Para evitar imprevistos, o candidato deve chegar aos locais de exame com uma hora de antecedência. Assim terá tempo para localizar sua sala. Os portões das escolas serão abertos às 12h30 e fechados às 13h30, impreterivelmente.</p><p>A demanda por curso e por unidade e a lista de locais de prova estão disponíveis no site www.vestibulinhoetec.com.br.</p></br><h1>Exame</h1><p>Para fazer a prova, é preciso levar caneta esferográfica de tinta preta ou azul, lápis preto nº 2, borracha, régua e o original de um dos seguintes documentos: cédula de identidade (RG); cédula de identidade de estrangeiros (RNE) dentro da validade; carteira nacional de habilitação (CNH) dentro da validade ou com até 30 dias do vencimento, conforme legislação em vigor; documento expedido por ordens ou conselhos profissionais, dentro da validade, que, por lei federal, vale como documento de identidade em todo o País (exemplo: OAB, Coren e Crea, entre outros); carteira de trabalho e previdência social (CTPS) ou passaporte brasileiro dentro da validade.</p><p>Exame – Primeiro módulo dos cursos do Ensino Técnico (presencial, semipresencial e online) e para o primeiro termo do Ensino Técnico Integrado ao Médio na modalidade EJA – A prova terá 50 questões de múltipla escolha, cada uma com cinco alternativas, relacionadas às diferentes áreas do saber (científico, artístico e literário), à comunicação e à expressão, em diversos tipos de linguagem, abrangendo conhecimentos comuns do Ensino Fundamental, de 5ª a 8ª série ou do 6º ao 9º ano.</p><p>O gabarito oficial da prova será divulgado no dia 16 de junho, a partir das 18 horas, nos sites www.cps.sp.gov.br e www.vestibulinhoetec.com.br.</p>',
     link:'/por-numero/9'},
    {titulo: 'Etecs superam Finlândia, Japão e Canadá no Pisa para Escolas', img:'https://www.cps.sp.gov.br/wp-content/uploads/sites/1/2019/06/pisa-fabio-580x420.jpg',
     resumo:'Quatro Escolas Técnicas Estaduais (Etecs) alcançaram resultados equivalentes ou superiores aos de países desenvolvidos na avaliação internacional de estudantes',
     conteudo:'<p>Quatro Escolas Técnicas Estaduais (Etecs) participantes em 2017 do Pisa para Escolas (Pisa for Schools em inglês, o Pisa-S), avaliação internacional de estudantes da Organização para a Cooperação e Desenvolvimento Econômico (OCDE), alcançaram resultados equivalentes ou superiores aos de países desenvolvidos. Os resultados foram apresentados nesta quinta-feira, 13, pela diretora-superintendente do Centro Paula Souza, Laura Laganá, na Conferência Internacional de Lançamento do Pisa para Escolas, no Rio.</p><p>O exame avalia a competência de estudantes de 15 anos em Leitura, Matemática e Ciências em todo o mundo. As unidades do Centro Paula Souza (CPS) participaram a convite da Fundação Lemann, que trouxe o Pisa-S para o Brasil com o objetivo de contribuir para a construção de políticas públicas baseadas em dados e evidências. Foram avaliadas 46 escolas brasileiras, da quais 13 eram particulares e 33, da rede pública.</p><p>As Etecs São Paulo (Etesp) e Guaracy Silveira, ambas na Capital, obtiveram notas mais elevadas que a média de países como Canadá, Finlândia, Japão, Polônia, Portugal, França, Reino Unido, Estados Unidos, Rússia, China e Chile em todas as três áreas.</p><p>Localizada na zona sul, no bairro com o quarto pior Índice de Desenvolvimento Humano (IDH) da Capital paulista, a Etec Jardim Ângela também superou a média desses países em Leitura e teve performance superior à média em Ciências de outros, como Reino Unido, Polônia e França. A Etec Profª Marinês Teodoro de Freitas Almeida, de Novo Horizonte, no noroeste do Estado, também foi destaque em Leitura, à frente de países como Portugal, Reino Unido e China, e, em Ciências, de França, Rússia e Polônia, entre outros.</p>',
     link:'/por-numero/10'}
  ]

  constructor(private rota: Router, private enviaDado: PassandoDadosService)  {
  }

  public mostraNoticia(noticia) {
    this.enviaDado.setDados('noticia', noticia);
    this.rota.navigate(['/detalhes-noticias']);
  }


}
